version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: reservoir
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    hasura:
        image: hasura/graphql-engine:latest
        container_name: hasura
        depends_on:
            - postgres
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/reservoir
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
        ports:
            - "8080:8080"
volumes:
    postgres_data:
    redis_data:
